name: 'fetcher for acclerator unit test files'
runs:
  using: 'composite'
  steps:
    - name: Download files
      run: |
        curl -Ls https://github.com/slaclab/accel_unit_test_execs/raw/main/mad8s -o "$PWD/mad8s"
        chmod +x "$PWD/mad8s"
        echo "$PWD" >> $GITHUB_PATH
      shell: bash
